// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kppoejwyebhxayjvxsaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwcG9land5ZWJoeGF5anZ4c2FmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExMzM3MTUsImV4cCI6MjA3NjcwOTcxNX0.y4wVAqMwy1iOv3JvHYR676t88TgIYl6J7IsQLHnDfE8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});